In [1]:
#importing necessary libraries
from sklearn import datasets
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler, LabelEncoder

from sklearn.model_selection import train_test_split, GridSearchCV

from sklearn.metrics import plot_confusion_matrix, confusion_matrix, accuracy_score

from sklearn.metrics import precision_score, precision_recall_curve, plot_precision_recall_curve, plot_roc_curve, roc_auc_score, roc_curve, f1_score, accuracy_score, recall_score

from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression

from sklearn.tree import DecisionTreeClassifier


In [2]:
 
df = pd.read_excel("GSOEP_data-set.xlsx")
df
 


Unnamed: 0       school  birthyear  gender  kids  parity         income  \
0             1    Gymnasium       1981  female     2       2   35160.113491   
1             2    Gymnasium       1981  female     2       2   65748.345269   
2             3    Gymnasium       1980  female     3       3  120962.356461   
3             4    Gymnasium       1984  female     1       1   60100.572300   
4             5   Realschule       1982    male     4       4   34828.951843   
..          ...          ...        ...     ...   ...     ...            ...   
670         671   Realschule       1986  female     3       1  163592.930460   
671         672  Hauptschule       1987  female     2       2   13790.686771   
672         673  Hauptschule       1984    male     5       1   63503.014678   
673         674    Gymnasium       1987    male     1       1   47978.267069   
674         675   Realschule       1987  female     2       1   31854.248668   

     size                     state   marital  meducation memployment  year  
0       4                    Berlin   married        14.5        none  1995  
1       3                    Berlin   married        10.5    parttime  1995  
2       3                    Berlin   married        12.0    parttime  1994  
3       3                    Berlin   married        10.5    parttime  1998  
4       4                    Berlin  divorced        10.0    fulltime  1996  
..    ...                       ...       ...         ...         ...   ...  
670     5        Schleswig-Holstein   married        12.0    parttime  2000  
671     2  Rheinland-Pfalz/Saarland  divorced        15.0    parttime  2001  
672     6             Niedersachsen   married        12.0        none  1998  
673     3             Niedersachsen   married        11.5        none  2001  
674     3        Baden Wuerttemberg  divorced        11.5    parttime  2001  

[675 rows x 13 columns]

In [3]:
#Get list of categorical variables
s = (df.dtypes == 'object')
object_cols = list(s[s].index)

print("Categorical variables in the dataset:", object_cols)

Categorical variables in the dataset: ['school', 'gender', 'state', 'marital', 'memployment']


In [4]:
#Label Encoding the object dtypes.
LE=LabelEncoder()
for i in object_cols:
    df[i]=df[[i]].apply(LE.fit_transform)
    
print("All features are now numerical")

All features are now numerical


In [5]:
# X -> features, y -> label
X = df.drop(["school"], axis=1)
y = df["school"]

# Decision Tree

In [6]:
# dividing X, y into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.1,random_state = 0)
 
# training a DescisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier
dtree_model = DecisionTreeClassifier(max_depth = 2).fit(X_train, y_train)
dtree_predictions = dtree_model.predict(X_test)
dtree_predictions



array([1, 2, 0, 0, 0, 0, 2, 0, 2, 0, 1, 0, 0, 1, 2, 0, 2, 0, 0, 1, 2, 2,
       1, 2, 0, 1, 2, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 1, 2, 1, 2, 0, 0, 0,
       1, 0, 0, 2, 2, 2, 1, 0, 0, 2, 2, 2, 2, 0, 0, 0, 2, 2, 1, 2, 0, 0,
       2, 0])

In [7]:
# creating a confusion matrix
cm = confusion_matrix(y_test, dtree_predictions)
cm

array([[17,  2,  3],
       [ 7,  6,  9],
       [ 8,  3, 13]], dtype=int64)

In [8]:
accuracy_score(y_test, dtree_predictions)

0.5294117647058824

# SVM

In [21]:
# dividing X, y into train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3,random_state = 0)

from sklearn.svm import SVC
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train)
svm_predictions = svm_model_linear.predict(X_test)
 
# model accuracy for X_test 
accuracy = svm_model_linear.score(X_test, y_test)
 
# creating a confusion matrix
cm = confusion_matrix(y_test, svm_predictions)
svm_predictions

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2, 1, 1, 0, 0, 1, 0, 0, 2, 0,
       1, 1, 0, 1, 1, 2, 1, 1, 0, 0, 2, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 2,
       1, 0, 0, 1, 2, 0, 0, 0, 0, 2, 0, 2, 1, 2, 2, 0, 2, 0, 1, 1, 0, 0,
       0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 2, 0, 1, 0, 2, 1,
       2, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 2, 0, 2, 1, 1, 0, 0, 1, 2, 0,
       1, 2, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       2, 0, 1, 2, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 2,
       2, 2, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 0, 1,
       0, 2, 0, 0, 0])

In [22]:
# creating a confusion matrix
cm = confusion_matrix(y_test, svm_predictions)
cm

array([[65,  9, 12],
       [23, 23, 11],
       [28, 17, 15]], dtype=int64)

In [23]:
accuracy_score(y_test, svm_predictions)

0.5073891625615764